name: my-first-workflow
on: 
  workflow_dispatch: 
    inputs: 
      name: 
        description: Provide a name
        required: true
        default: test
  schedule:
    - cron: '*/15 * * * *'

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
     - run: |
        echo "Hello ${{inputs.name}}"
